#!/bin/bash

bntmp="/tmp/brown-noise-pid"
[[ -e "$bntmp" ]] && {
    kill "$(cat "$bntmp")"
    rm -f "$bntmp"
    killall dunst
    notify-send -t 4000 "Brown noise off"
} || {
    bnfile="$HOME/.local/share/user-scripts/sounds/brown-noise.flac"
    [[ ! -e "$bnfile" ]] && {
	notify-send -t 4000 -u critical "ERROR" "Brown noise file does not exist."
	exit 1
    }
    quodlibet --pause
    pamixer --set-volume 60
    mpv \
	--really-quiet     \
	--loop=inf         \
	--profile=fast     \
	--no-audio-display \
	--no-video         \
	--volume-max=120   \
	--volume=120       \
	"$bnfile" &
    bnpid="$(pgrep -f "${bnfile##*/}")"
    if ! ps -p "$bnpid" > /dev/null || [[ -z "$bnpid" ]]
    then
	notify-send -t 10000 -u critical "ERROR" "Failed to extract PID"
	pkill -f "mpv.*brown-noise.mp3"
	exit 1
    fi
    echo -n "$bnpid" > "$bntmp"
    killall dunst
    notify-send -t 4000 "Brown noise on"
}
