#!/bin/bash
source "$HOME"/Repositories/private/private-aliases.sh

[[ -z "$BLUETOOTH_HEADPHONES" ]] && {
    notify-send -t 2000 'Address of Bluetooth headphones unknown.'
}

bluetoothctl info "$BLUETOOTH_HEADPHONES" | grep -q 'Battery Percentage' && {
    dunstctl close-all
    notify-send -t 2000 'Already connected.'
} || {
    dunstctl close-all
    notify-send -t 2000 'Connecting to Bluetooth headphones...'
    bluetoothctl connect "$BLUETOOTH_HEADPHONES" && {
	dunstctl close-all
	notify-send -t 2000 'Connected successfully!'
    } || {
	dunstctl close-all
	notify-send -t 2000 'Connection failed!'
    }
}
    
