#!/bin/bash

touch /tmp/current-song
inotifywait -qme modify /tmp/current-song \
    | {
    while read -r
    do
	dunstctl close-all
	notify-send -t 2000 "$(cat /tmp/current-song-full | sed 's/ - /\n/g;s/ — /\n/')"
    done
}
