#!/bin/bash
source ~/Repositories/scripts/essential-functions
watch_history_yt="$HOME/Misc/Backups/video/watch-history-youtube.csv"
watch_history_gen="$HOME/Misc/Backups/video/watch-history-general.csv"
watch_history_docs="$HOME/Misc/Backups/video/watch-history-docs.csv"
watch_history_tv="$HOME/Misc/Backups/video/watch-history-tv.csv"
watch_history_film="$HOME/Misc/Backups/video/watch-history-film.csv"

case "$1" in
    "yt"|"youtube")
	tail -n 24 "$watch_history_yt" | xan view -MRn --color=always --theme="striped" | sed '/^$/d'
	;;
    "gen"|"general"|"misc")
	tail -n 24 "$watch_history_gen" | xan view -MRn --color=always --theme="striped" | sed '/^$/d'
	;;
    "tv"|"show"|"shows")
	tail -n 24 "$watch_history_tv" | xan view -MRn --color=always --theme="striped" | sed '/^$/d'
	;;
    "doc"|"docs"|"documentaries"|"documentary")
	tail -n 24 "$watch_history_docs" | xan view -MRn --color=always --theme="striped" | sed '/^$/d'
	;;
    "film"|"films"|"movies"|"movie")
	tail -n 24 "$watch_history_film" | xan view -MRn --color=always --theme="striped" | sed '/^$/d'
	;;
    "hist"|"history"|"all")
	echo -n YouTube
	tail -n 3 "$watch_history_yt"  | ifne xan view -MRn --color=always --theme="striped" | sed '/^$/d' 
	echo -n TV
	tail -n 3 "$watch_history_tv" | ifne xan view -MRn --color=always --theme="striped" | sed '/^$/d'	    
	echo -n Documentaries
	tail -n 3 "$watch_history_docs" | ifne xan view -MRn --color=always --theme="striped" | sed '/^$/d'	    
	echo -n Films
	tail -n 3 "$watch_history_film" | ifne xan view -MRn --color=always --theme="striped" | sed '/^$/d'	    
	echo -n General
	tail -n 3 "$watch_history_gen" | ifne xan view -MRn --color=always --theme="striped" | sed '/^$/d'	    
	;;
    "fav"|"star"|"stars"|"starred")
	echo '🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟'
	rg -N '🌟' "$watch_history_yt" |                       \
	    xan select -n 0,1                                   \
	    | sed 's/🌟//g'                                     \
	    | sort                                              \
	    | uniq                                              \
	    | cut -c 18-                                        \
	    | xan view -MRn --color=always --theme="striped"
	echo '🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟'
	;;
    *)
	:
	;;
esac
	

vid_exts=
[[ -z "$1" ]] || exit

ep="$(eza --no-quotes -1fX --show-symlinks | sed '/^$/d' | sort | grep -E 'mkv$|avi$|mp4$|ts$|mov$|webm$|m4v$' | ifne fzf)"
[[ -z "$ep" ]] && {
    echolor yellow ":: No file selected."
    exit
}
[[ -e "$HOME/Excluding/youtube/.${ep%mp4}json" ]] && {
    echo -n 'Uploaded '
    date -Idate -d "$(jq -r '.upload_date' "$HOME/Excluding/youtube/.${ep%mp4}json")"
    echo -n 'Downloaded '
    date -Idate -d "$(stat -c '%w' "$ep")"
}
[[ -e "$HOME/Excluding/youtube/.${ep%mp4}json" ]] && jq -r '.description' "$HOME/Excluding/youtube/.${ep%mp4}json" | bat -pp 
mpv --osd-fractions --volume=100 --volume-max=200 --alang=eng --slang=eng "$ep" || exit
choose_done="$(echo -e 'Mark as done\nDo nothing\nAbandon file\nDone and star' | fzf --no-input)"
ext_alone="$(echo "$ep" | awk -F '.' '{print $NF}')"
allrelatedfiles="$(echo "$ep" | sed "s/\.$ext_alone//;s/,/‚/g")"
addstar=''
[[ "$choose_done" = "Done and star" ]] && addstar='🌟'
case "$choose_done" in
    "Mark as done"|"Done and star")
	if pwd | grep -q "$HOME/Excluding/youtube"
	then
	    {
		echo -ne "$addstar$allrelatedfiles,"
		echo -ne "$(jq '.channel' "$HOME/Excluding/youtube/.$allrelatedfiles".json),"
		echo  -e "$(date -Isec)"
	    } >> "$watch_history_yt"
	    move-to-trash-recursively "$allrelatedfiles"* "$HOME/Excluding/youtube/.$allrelatedfiles".json
	    echolor green ":: Logged into the YouTube record $addstar"
	elif pwd | grep -q "$HOME/TV"
	then
	    {
		echo -ne "$(pwd | awk -F '/' '{print $5}'),"
		echo -ne "$(tr -d ',' <<< "$allrelatedfiles"),"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_tv"
       	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the TV record"
	elif pwd | grep -q "$HOME/Excluding/documentaries"
	then
	    {
		echo -ne "$allrelatedfiles,"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_docs"
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the documentaries record"
	elif pwd | grep -q "$HOME/Films"
	then
	    {
		echo -ne "$allrelatedfiles,"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_film"
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the film record"
	else
	    {
		echo -ne "$allrelatedfiles,"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_gen"
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the general record"
	fi
	;;
    "Abandon file")
	if pwd | grep -q "$HOME/Excluding/youtube"
	then
	    move-to-trash-recursively "$allrelatedfiles"* "$HOME/Excluding/youtube/.$allrelatedfiles".json
	    echolor yellow ":: The video ““$allrelatedfiles””\n:: has been abandoned"
	elif pwd | grep -q "$HOME/TV"
	then
       	    move-to-trash-recusively "$allrelatedfiles"*
	    echolor yellow ":: The episode ““$allrelatedfiles””\n:: has been abandoned"
	elif pwd | grep -q "$HOME/Excluding/documentaries"
	then
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The documentary ““$allrelatedfiles””\n:: has been abandoned"
	elif pwd | grep -q "$HOME/Films"
	then
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The film ““$allrelatedfiles””\n:: has been abandoned"
	else
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The file ““$allrelatedfiles””\n:: has been abandoned"
	fi
	;;
    "Do nothing")
	echolor yellow ":: Nothing was done"
	;;
esac
