#!/bin/bash
source ~/Repositories/scripts/essential-functions
watch_history_yt="$HOME/Misc/Backups/video/watch-history-youtube.csv"
watch_history_gen="$HOME/Misc/Backups/video/watch-history-general.csv"
watch_history_docs="$HOME/Misc/Backups/video/watch-history-docs.csv"
watch_history_tv="$HOME/Misc/Backups/video/watch-history-tv.csv"
watch_history_film="$HOME/Misc/Backups/video/watch-history-film.csv"

[[ ! -e "$watch_history_yt" ]] && {
    echolor yellow ":: ““$watch_history_yt”” created"
    echo "title,channel,duration,time" > "$watch_history_yt"
} 
[[ ! -e "$watch_history_gen" ]] && {
    echolor yellow ":: ““$watch_history_gen”” created"
    echo "title,time" > "$watch_history_gen"
} 
[[ ! -e "$watch_history_docs" ]] && {
    echolor yellow ":: ““$watch_history_docs”” created"
    echo "title,time" > "$watch_history_docs"
} 
[[ ! -e "$watch_history_tv" ]] && {
    echolor yellow ":: ““$watch_history_tv”” created"
    echo "show,episode,time" > "$watch_history_tv"
} 
[[ ! -e "$watch_history_film" ]] && {
    echolor yellow ":: ““$watch_history_film”” created"
    echo "title,time" > "$watch_history_film"
} 

function channel-views {
    xan select channel,duration "$watch_history_yt"        \
	| xan groupby channel 'count(channel) as views'    \
	| xan sort -NR -s views                            \
	| xan enum -S 1 -c rank
}

function channel-watchtimes {
    xan select channel,duration "$watch_history_yt"           \
	| xan groupby channel 'sum(duration) as duration'     \
	| xan sort -NR -s duration                            \
	| xan transform duration 'idiv(duration, 60)'         \
	| xan enum -S 1 -c rank
}

case "$1" in
    "yt"|"youtube")
	xan view -s title,channel,time -HMR --cols 0.9 --color=always --theme="striped" -l 23 "$watch_history_yt" | sed '/^$/d'
	;;
    "gen"|"general"|"misc")
        xan view -HMR --color=always --theme="striped" -l 23 "$watch_history_gen" | sed '/^$/d'
	;;
    "tv"|"show"|"shows")
	xan view -HMR --cols 0.99 --color=always --theme="striped" -l 23 "$watch_history_tv" | sed '/^$/d'
	;;
    "doc"|"docs"|"documentaries"|"documentary")
	xan view -HMR --color=always --theme="striped" -l 23 "$watch_history_docs" | sed '/^$/d'
	;;
    "film"|"films"|"movies"|"movie"|"mov")
	xan view -HMR --color=always --theme="striped" -l 23 "$watch_history_film" | sed '/^$/d'
	;;
    "hist"|"history"|"all")
	echo -n "YouTube ($(xan count "$watch_history_yt"))"
	xan select title,channel,time "$watch_history_yt" | xan behead | tail -n 3 | ifne xan view -nMR --color=always --theme="striped" | sed '/^$/d' 
	echo -n "TV ($(xan count "$watch_history_tv"))"
	xan behead "$watch_history_tv" | tail -n 3 | ifne xan view -nMR --color=always --theme="striped" | sed '/^$/d'	    
	echo -n "Documentaries ($(xan count "$watch_history_docs"))"
	xan behead "$watch_history_docs" | tail -n 3 | ifne xan view -nMR --color=always --theme="striped" | sed '/^$/d'	    
	echo -n "Films ($(xan count "$watch_history_film"))"
	xan behead "$watch_history_film" | tail -n 3 | ifne xan view -nMR --color=always --theme="striped" | sed '/^$/d'	    
	echo -n "General ($(xan count "$watch_history_gen"))"
	xan behead "$watch_history_gen" | tail -n 3 | ifne xan view -nMR --color=always --theme="striped" | sed '/^$/d'	    
	;;
    "fav"|"star"|"stars"|"starred")
	echo '🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟'
	xan select title,channel "$watch_history_yt"             \
	    | rg -N '🌟'                                        \
	    | sed 's/🌟//g'                                     \
	    | sort                                              \
	    | uniq                                              \
	    | cut -c 18-                                        \
	    | xan view -nMR --color=always --theme="striped"
	echo '🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟'
	;;
    "rank"|"channel"|"channels")
#	channel-watchtimes | xan view -MRIpA
	xan cat columns <(channel-views | xan select views,channel) <(channel-watchtimes) | xan view -MRIpAr 1
	;;
    *)
	:
	;;
esac
	

vid_exts=
[[ -z "$1" ]] || exit

ep="$(eza --no-quotes -1fX --show-symlinks | sed '/^$/d' | sort | grep -E 'mkv$|avi$|mp4$|ts$|mov$|webm$|m4v$' | ifne fzf)"
[[ -z "$ep" ]] && {
    echolor yellow ":: No file selected."
    exit
}
[[ -e "$HOME/Excluding/youtube/.${ep%mp4}json" ]] && {
    echolor white 'Title:  \t' 1
    jq -r '.title' "$HOME/Excluding/youtube/.${ep%mp4}json" | sed 1q
    echolor white 'Channel:\t' 1
    jq -r '.channel' "$HOME/Excluding/youtube/.${ep%mp4}json" | sed 1q
    echolor white 'Uploaded:\t' 1
    date -Idate -d "$(jq -r '.upload_date' "$HOME/Excluding/youtube/.${ep%mp4}json" | sed 1q)"
    echolor white 'Downloaded:\t' 1
    date -Idate -d "$(stat -c '%w' "$ep")"
    echolor white 'Times watched:\t' 1
    watch_instance="$(rg -- "$(echo "$ep" | between '[' ']')" "$watch_history_yt" | wc -l)"
    echo "$watch_instance"
    channel="$(jq -r '.channel' "$HOME/Excluding/youtube/.${ep%mp4}json" | sed 1q)"
    echolor white 'View rank:\t' 1
    echo -n "#$(channel-views | xan search -s channel -e "$channel" | xan select rank | xan behead) by views ("
    echo -n "$(channel-views | xan search -s channel -e "$channel" | xan select views | xan behead) times)"
    echo
    echolor white 'Time rank:\t' 1
    echo -n "#$(channel-watchtimes | xan search -s channel -e "$channel" | xan select rank | xan behead) by watchtime ("
    echo -n "$(channel-watchtimes | xan search -s channel -e "$channel" | xan select duration | xan behead) minutes)"
    echo
    echolor white '------------------------------------------------------'
}
[[ -e "$HOME/Excluding/youtube/.${ep%mp4}json" ]] && {
    jq -r '.description' "$HOME/Excluding/youtube/.${ep%mp4}json" | fold -sw 130
    echolor white '------------------------------------------------------'
}
mpv --msg-level=all=error --osd-fractions --volume=100 --volume-max=200 --alang=eng --slang=eng "$ep" || exit
choose_done="$(echo -e 'Mark as done\nDo nothing\nAbandon file\nDone and star' | fzf --no-input)"
ext_alone="$(echo "$ep" | awk -F '.' '{print $NF}')"
allrelatedfiles="$(echo "$ep" | sed "s/\.$ext_alone//;s/,/‚/g")"
addstar=''
[[ "$choose_done" = "Done and star" ]] && addstar='🌟'
case "$choose_done" in
    "Mark as done"|"Done and star")
	if pwd | grep -q "$HOME/Excluding/youtube"
	then
	    {
		echo -ne "$addstar$allrelatedfiles,"
		echo -ne "$(jq '.channel' "$HOME/Excluding/youtube/.$allrelatedfiles".json | sed 1q),"
		echo -ne "$(jq '.duration' "$HOME/Excluding/youtube/.$allrelatedfiles".json | sed 1q),"
		echo  -e "$(date -Isec)"
	    } >> "$watch_history_yt"
	    move-to-trash-recursively "$allrelatedfiles"* "$HOME/Excluding/youtube/.$allrelatedfiles".json
	    echolor green ":: Logged into the YouTube record $addstar"
	elif pwd | grep -q "$HOME/TV"
	then
	    {
		echo -ne "$(pwd | awk -F '/' '{print $5}'),"
		echo -ne "$(tr -d ',' <<< "$allrelatedfiles"),"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_tv"
       	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the TV record"
	elif pwd | grep -q "$HOME/Excluding/documentaries"
	then
	    {
		echo -ne "$allrelatedfiles,"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_docs"
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the documentaries record"
	elif pwd | grep -q "$HOME/Films"
	then
	    {
		echo -ne "$allrelatedfiles,"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_film"
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the film record"
	else
	    {
		echo -ne "$allrelatedfiles,"
		echo -e "$(date -Isec)"
	    } >> "$watch_history_gen"
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor green ":: Logged into the general record"
	fi
	;;
    "Abandon file")
	if pwd | grep -q "$HOME/Excluding/youtube"
	then
	    move-to-trash-recursively "$allrelatedfiles"* "$HOME/Excluding/youtube/.$allrelatedfiles".json
	    echolor yellow ":: The video ““$allrelatedfiles””\n:: has been abandoned"
	elif pwd | grep -q "$HOME/TV"
	then
       	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The episode ““$allrelatedfiles””\n:: has been abandoned"
	elif pwd | grep -q "$HOME/Excluding/documentaries"
	then
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The documentary ““$allrelatedfiles””\n:: has been abandoned"
	elif pwd | grep -q "$HOME/Films"
	then
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The film ““$allrelatedfiles””\n:: has been abandoned"
	else
	    move-to-trash-recursively "$allrelatedfiles"*
	    echolor yellow ":: The file ““$allrelatedfiles””\n:: has been abandoned"
	fi
	;;
    "Do nothing")
	echolor yellow ":: Nothing was done"
	;;
esac
