#!/bin/bash
source ~/Repositories/scripts/essential-functions

webfile="$HOME/.local/share/user-scripts/websites.csv"
unset chosensite
chosensite="$(xsv select -n 1 "$webfile" | rofi -normalize-match -dmenu -i)"
[[ -z "$chosensite" ]] && exit 1
xsv search -n "^$chosensite" "$webfile"  | xsv select 2 | ifne xargs xdg-open
