#!/bin/bash
source ~/Repositories/scripts/essential-functions

[[ -z "$1" ]] && exit 1
name_orig="$1"

function segment {
    :
}



while getopts 'n:' OPTION; do
    case "$OPTION" in
	"a") seq="$OPTARG" ;;
	esac
done
# (( $OPTIND == 1 )) && 

