#!/bin/bash
source ~/Repositories/scripts/essential-functions

[[ "$1" = "inquire" ]] && {
    find /tmp/ -name "ThyPipe-downloading*" 2>/dev/null | wc -l
    exit 0
}

thypipe_dir="$HOME/Excluding/youtube"
hezi_file="$thypipe_dir/.rules.hezi"
function detect-lang {
    test_stump="$(echo "$1" | tr -d '[’a-zA-Z[:punct:][:digit:][:space:]]…＂：∶–-—⧸｜？’‘')"
    [[ -z "$test_stump" ]] && return 1
    if ! cmp -s <(echo "$1") <(echo "$1" | iconv -c -f utf8 -t ascii//TRANSLIT)
    then
	if echo "$1" | grep -qP '\P{ASCII}'
	   # \P in pcresyntax(3) manual
	   # https://perldoc.perl.org/perlrecharclass#Unicode-Properties
	then
	    return 0 # yes translate
	else
	    return 1 # no translate
	fi
    else
	return 1
    fi    
}

function hezifier {
    [[ -e "$hezi_file" ]] || return 1
    function trim-spaces {
	sed 's/^ *//g;s/ *$//g; s/  */ /g'
    }
    function interpret-matcher {
       	grep -q "=" <<< "$1" && {
	    operation="equality"
	    field="$(awk -F '=' '{print $1}' <<< "$1" | trim-spaces)"
	    statement="$(awk -F '=' '{print $2}' <<< "$1" | trim-spaces)"
	    return
	}
	grep -q "%" <<< "$1" && {
	    operation="contains"
	    field="$(awk -F '%' '{print $1}' <<< "$1" | trim-spaces)"
	    statement="$(awk -F '%' '{print $2}' <<< "$1" | trim-spaces)"
	    return
	}
    }
    while read line
    do
	[[ "$line" = "end rules" ]] && break
	matcher="$(awk -F '→' '{print $1}' <<< "$line" | trim-spaces)"
	hezicle="$(awk -F '→' '{print $2}' <<< "$line" | trim-spaces | kebab)"
	[[ -z "$matcher" || -z "$hezicle" ]] && continue
	interpret-matcher "$matcher"
	echo -e "hezi results: matcher '$matcher' hezicle '$hezicle' operation '$operation' field '$field' statement '$statement'" \
	     >> "/tmp/ThyPipe-downloading-$id"
	[[ "$operation" = "equality" ]] && {
	    [[ "$(jq -r ".$field" "$tmp")" = "$statement" ]] && {
		mkdir "$thypipe_dir"/"$(kebab "$hezicle")"
		echo "MATCHED! line '$line'" >> "/tmp/ThyPipe-downloading-$id"
		echo -n "$hezicle"
		return
	    }
	}
	[[ "$operation" = "contains" ]] && {
	    jq -r ".$field" "$tmp" | grep -q "$statement" && {
		mkdir "$thypipe_dir"/"$(kebab "$hezicle")"
		echo "MATCHED! line '$line'" >> "/tmp/ThyPipe-downloading-$id"
		echo -n "$hezicle"
		return
	    }
	}
	hezicle=''
    done < "$hezi_file"
}

id="$(awk -F 'v=' '{print $NF}' <<< "$1")"
touch "/tmp/ThyPipe-downloading-$id"
notify-send -u low -t 1000 "ThyPipe" "Extracting $1"
tmp="/tmp/ThyPipe-$(date-string)-$(random-string 12)-$id.json"
yt-dlp -j --use-postprocessor DeArrow:when=pre_process "$1" 2>> "/tmp/ThyPipe-ytdlplog-1-$(date-string)-$id.log" 1> "$tmp" || {
    notify-send -u critical -t 4000 "ThyPipe" "Video $1 failed to extract"
    mv "/tmp/ThyPipe-downloading-$id" "/tmp/ThyPipe-errorjson-$id-$(date-string)-$(random-string)"
    exit 1
}
title_raw="$(jq -r '.title' "$tmp")"
detect-lang "$title_raw" && {
    title="$(trans -b :en "$title_raw" | kebab)"
} || {
    title="$(kebab "$title_raw")"
}
[[ -z "$title" || -z "$id" ]] && {
    notify-send -u critical -t 4000 "ThyPipe" "Information missing for Video\n$1"
    echo -e "$title_raw\n$title\n$id" >> "/tmp/ThyPipe-downloading-$id"
    mv "/tmp/ThyPipe-downloading-$id" "/tmp/ThyPipe-erroremptyinfo-$id-$(date-string)-$(random-string)"
    exit 1
}
echo "$title-[$id].mp4" >> "/tmp/ThyPipe-downloading-$id"
notify-send -u low -t 1000 "ThyPipe" "Downloading video \"$title\" now"
yt-dlp \
    -f 'bestvideo[height=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'        \
    --fragment-retries infinite                                                       \
    --no-mtime --embed-chapters --embed-subs --sub-langs en,-live_chat                \
    --use-postprocessor DeArrow:when=pre_process --remote-components ejs:github       \
    --extractor-args "youtube:player-client=default,-tv_simply,-android_sdkless"      \
    --no-playlist -o "$title-[$id].%(ext)s" -P "/tmp/"                                \
    "$1" 2>> "/tmp/ThyPipe-ytdlplog-2-$(date-string)-$id.log" || {
    notify-send -u critical -t 4000 "ThyPipe" "Errors detected while downloading video \"$title\""
}
[[ ! -e "/tmp/$title-[$id].mp4" ]] && {
    notify-send -u critical -t 4000 "ThyPipe" "Did not find video $1 after download!"
    mv "/tmp/ThyPipe-downloading-$id" "/tmp/ThyPipe-errormissingfile-$id-$(date-string)-$(random-string)"
    exit 1
}
hezicle=$(hezifier)
[[ -z "$hezicle" ]] && hezicle="main"
mv /tmp/"$title"*']'.mp4 "$thypipe_dir/$hezicle" || {
    notify-send -u critical -t 4000 "ThyPipe" "Failed to move \"$1\""
    mv "/tmp/ThyPipe-downloading-$id" "/tmp/ThyPipe-errorcantmv-$id-$(date-string)-$(random-string)"
    exit 1
}
echo -e "$(jq '.description' "$tmp")" > "$thypipe_dir/.$title-[$id].dooblydoo"
mv "/tmp/ThyPipe-downloading-$id" "/tmp/ThyPipe-done-$id-$(date-string)-$(random-string)"
notify-send -t 4000 "ThyPipe" "Video \"$title\" successfully downloaded!"
    
